export default {
  id: "root",
  name: "Page",
  props: {},
  isContainer: true,
  children: [
    {
      name: "Image",
      isContainer: false,
      props: {
        attr: {
          src: "https://picsum.photos/200/300?1720684555989",
          title: "image",
        },
        style: {
          borderTopLeftRadius: 0,
          color: "#000000",
          paddingTop: 0,
          borderTopRightRadius: 0,
          borderStyle: "solid",
          width: 200,
          marginTop: 0,
          height: 300,
          fontWeight: "normal",
          opacity: 1,
          paddingRight: 0,
          backgroundImage: "",
          marginRight: 0,
          borderBottomLeftRadius: 0,
          fontSize: 14,
          marginLeft: 0,
          backgroundColor: "#ffffff",
          borderColor: "#000000",
          borderBottomRightRadius: 0,
          textAlign: "left",
          paddingLeft: 0,
          marginBottom: 0,
          borderWidth: 0,
          lineHeight: "normal",
          paddingBottom: 0,
        },
      },
      isPanel: false,
      id: "1720684557865_1",
    },
    {
      name: "Button",
      isContainer: false,
      props: {
        attr: {
          text: "按钮文本",
        },
        style: {
          outline: "none",
          borderTopLeftRadius: 0,
          color: "white",
          paddingTop: 0,
          borderTopRightRadius: 0,
          borderStyle: "solid",
          width: 100,
          userSelect: "none",
          marginTop: 0,
          height: 50,
          fontWeight: "bold",
          opacity: 1,
          paddingRight: 0,
          backgroundImage: "",
          marginRight: 0,
          borderBottomLeftRadius: 0,
          fontSize: 16,
          marginLeft: 0,
          backgroundColor: "#5584ff",
          cursor: "pointer",
          borderColor: "#000000",
          borderBottomRightRadius: 0,
          textAlign: "center",
          paddingLeft: 0,
          marginBottom: 0,
          borderWidth: 0,
          lineHeight: "50px",
          paddingBottom: 0,
          borderRadius: 5,
        },
      },
      isPanel: false,
      id: "1720685094112_1",
    },
    {
      name: "Button",
      isContainer: false,
      props: {
        attr: {
          text: "按钮文本",
        },
        style: {
          outline: "none",
          borderTopLeftRadius: 0,
          color: "white",
          paddingTop: 0,
          borderTopRightRadius: 0,
          borderStyle: "solid",
          width: 100,
          userSelect: "none",
          marginTop: 0,
          height: 50,
          fontWeight: "bold",
          opacity: 1,
          paddingRight: 0,
          backgroundImage: "",
          marginRight: 0,
          borderBottomLeftRadius: 0,
          fontSize: 16,
          marginLeft: 0,
          backgroundColor: "#5584ff",
          cursor: "pointer",
          borderColor: "#000000",
          borderBottomRightRadius: 0,
          textAlign: "center",
          paddingLeft: 0,
          marginBottom: 0,
          borderWidth: 0,
          lineHeight: "50px",
          paddingBottom: 0,
          borderRadius: 5,
        },
      },
      isPanel: false,
      id: "1720685095402_2",
    },
    {
      name: "Button",
      isContainer: false,
      props: {
        attr: {
          text: "按钮文本",
        },
        style: {
          outline: "none",
          borderTopLeftRadius: 0,
          color: "white",
          paddingTop: 0,
          borderTopRightRadius: 0,
          borderStyle: "solid",
          width: 100,
          userSelect: "none",
          marginTop: 0,
          height: 50,
          fontWeight: "bold",
          opacity: 1,
          paddingRight: 0,
          backgroundImage: "",
          marginRight: 0,
          borderBottomLeftRadius: 0,
          fontSize: 16,
          marginLeft: 0,
          backgroundColor: "#5584ff",
          cursor: "pointer",
          borderColor: "#000000",
          borderBottomRightRadius: 0,
          textAlign: "center",
          paddingLeft: 0,
          marginBottom: 0,
          borderWidth: 0,
          lineHeight: "50px",
          paddingBottom: 0,
          borderRadius: 5,
        },
      },
      isPanel: false,
      id: "1720685096511_3",
    },
    {
      name: "Image",
      isContainer: false,
      props: {
        attr: {
          src: "https://picsum.photos/200/300?1720685081897",
          title: "image",
        },
        style: {
          borderTopLeftRadius: 0,
          color: "#000000",
          paddingTop: 0,
          borderTopRightRadius: 0,
          borderStyle: "solid",
          width: 200,
          marginTop: 0,
          height: 300,
          fontWeight: "normal",
          opacity: 1,
          paddingRight: 0,
          backgroundImage: "",
          marginRight: 0,
          borderBottomLeftRadius: 0,
          fontSize: 14,
          marginLeft: 0,
          backgroundColor: "#ffffff",
          borderColor: "#000000",
          borderBottomRightRadius: 0,
          textAlign: "left",
          paddingLeft: 0,
          marginBottom: 0,
          borderWidth: 0,
          lineHeight: "normal",
          paddingBottom: 0,
        },
      },
      isPanel: false,
      id: "1720685098627_4",
    },
    {
      name: "Text",
      isContainer: false,
      props: {
        attr: { text: "文本内容" },
        style: {
          borderTopLeftRadius: 0,
          color: "#000000",
          paddingTop: 0,
          borderTopRightRadius: 0,
          borderStyle: "solid",
          width: "100%",
          marginTop: 0,
          height: "auto",
          fontWeight: "normal",
          opacity: 1,
          paddingRight: 0,
          backgroundImage: "",
          marginRight: 0,
          borderBottomLeftRadius: 0,
          fontSize: 14,
          marginLeft: 0,
          backgroundColor: "#ffffff",
          borderColor: "#000000",
          borderBottomRightRadius: 0,
          textAlign: "left",
          paddingLeft: 0,
          marginBottom: 0,
          borderWidth: 0,
          lineHeight: "normal",
          paddingBottom: 0,
        },
      },
      isPanel: false,
      id: "1720685100358_5",
    },
  ],
};
